CONFIG_ZMK_USB_LOGGING=n

# Fetch the battery level from the peripheral half
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Expose both battery levels over BLE
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y

CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
